version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: "todo-database"
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
    restart: always

  todo-backend:
    container_name: 'todo-server'
    build: ./backend
    environment:
      MONGODB_URI: "mongodb://todo-database"
    ports:
      - 4000:4000 
    links:
      - mongodb
    depends_on:
      - mongodb

  todo-frontend:
    container_name: 'todo-client'
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - /frontend/.next
    ports:
      - 3000:3000 
    links:
      - todo-backend

volumes:
  mongodata:
